### ISSUE TITLE
GUI don't open

### ISSUE THREAD

**Issue by LLAFTeamKiwi** [1Euro7Cent/Mrballou-drawbot#1]
The gui don't open and i only see "listining in 1337"

**Comment by 1Euro7Cent** [comment]
If that is the only console opened then you have a problem on the python site. Can you please try to open the gui.py by typing `python gui.py` and send me errors that eventually come up?

**Comment by 1Euro7Cent** [comment]
And u need the `tkinter` default python module. If you don't have it rerun the installation and click modify and check the checkbox where it says `tkinter`

**Comment by 1Euro7Cent** [comment]
I updated the README and maybe you don't have `requests` installed (`pip install requests`)
