### ISSUE TITLE
Please help I have been trying to download this for an hour now!

### ISSUE THREAD

**Issue by ToastedBread160** [1Euro7Cent/Mrballou-drawbot#10]
C:\Users\******\Desktop\Mrballou-drawbot-main>echo off
Traceback (most recent call last):
  File "C:\Users\******\Desktop\Mrballou-drawbot-main\gui.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Press any key to continue . . .

I really am just confused at this point I've tried so much I'm beginning to think it's not worth it...

**Comment by 1Euro7Cent** [comment]
That is a easy fix: `pip install requests`

**Comment by ToastedBread160** [comment]
I tryed "$ python -m pip install requests" in python but it dont do anything. Im also retarded so it would be much appreciated for a little more context.

**Comment by ToastedBread160** [comment]
if it helps it says listening on 49152

**Comment by ToastedBread160** [comment]
its on the server aswell, the python seems to be working fine.

**Comment by ToastedBread160** [comment]
Sorry I take so long to respond I have a lot of things to do during the day.

**Comment by ToastedBread160** [comment]
idk
![Screenshot 2022-02-18 233444](https://user-images.githubusercontent.com/99862798/154791674-946f6ff4-5078-437f-8770-f569fc7cd6c1.png)

**Comment by ToastedBread160** [comment]
this is what happens when i press start all

**Comment by 1Euro7Cent** [comment]
Go to the windows symbol and type cmd. Hit enter. Then type `pip install requests pynput` that should install all dependencies that are not installed by default

**Comment by ToastedBread160** [comment]
Thanks for the help with that but a new issue has emerged. Every time I try to use an image by URL it says it is too big even when  it is as small as 128x128

**Comment by ToastedBread160** [comment]
max dimentions: 410 228
(node:3668) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'bitmap' of undefined
    at resize (C:\snapshot\server\index.js)
    at Jimp.<anonymous> (C:\snapshot\server\index.js)
    at Timeout._onTimeout (C:\snapshot\server\node_modules\@jimp\core\dist\index.js:264:25)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:3668) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

**Comment by 1Euro7Cent** [comment]
It seems like there is a.error reading that image. Ima look into that when im at my pc.
Is that the beta? And can you send me that image that are you trying to do

**Comment by ToastedBread160** [comment]
idk if its the beta

**Comment by ToastedBread160** [comment]
https://images.app.goo.gl/zaPVf6fH8bpaAFGy7

**Comment by ToastedBread160** [comment]
i am just trying to test if it works with different images right now

**Comment by 1Euro7Cent** [comment]
The beta is it when you downloaded it from [here](https://github.com/1Euro7Cent/Mrballou-drawbot/tree/beta). The problem: that link doesnt end with .png or .jpg or .gif ect. That is a google search link. You can download the image and instead of the link put the full path to that image

**Comment by 1Euro7Cent** [comment]
Too inactive. Closing issue. Feel free to reopen when you still have something to contribute to this issue.
