### ISSUE TITLE
Drawbot goes out of bounds

### ISSUE THREAD

**Issue by polyqubit** [1Euro7Cent/Mrballou-drawbot#19]
All directions were followed in initializePositions, but upon running the drawbot the bot attempts to draw an image that is offset from the set boundaries
![image](https://user-images.githubusercontent.com/89955098/231833839-63aa2bab-dc08-4644-b5a2-af4238491762.png)

**Comment by polyqubit** [comment]
It might be a resizing issue because when I tried a portrait image, it drew a few dots on the canvas and then clicked randomly on the taskbar

**Comment by 1Euro7Cent** [comment]
It is capped at the defined area. Even if it wanted it cannot go outside except for color selection. It could be the problem that you don't configured it correctly, or you have screen zoom activated in windows (see image).

![image](https://user-images.githubusercontent.com/67194495/231842573-c151c3eb-a3fc-4126-8dc8-898aa31c9848.png)

**Comment by 1Euro7Cent** [comment]
Do you still have the issue?

**Comment by 1Euro7Cent** [comment]
Too inactive. Closing issue. Feel free to reopen when you still have something to contribute to this issue.
