### ISSUE TITLE
Program can't use configurations in config.json

### ISSUE THREAD

**Issue by 4c30** [1Euro7Cent/Mrballou-drawbot#2]
i have an uncommon screen resolution so i had to create a new layout for drawing on paint
i created a config named "paintduplicate" using initialisation.exe but when i insert the name in the gui, the command prompt says "invalid platform"

the message only doesn't show when i use exactly "skribbl", "gartic", and "paint", but those are probably default settings and they don't work well with my screen

edit: i forgot to mention that i'm using the new .exe release, i have no experience with the source files
i'm using python 3.9.4

here are some screenshots
![init](https://user-images.githubusercontent.com/82720819/115122267-4cb9ab00-9fb7-11eb-9cf2-d2180932e328.png)
![json](https://user-images.githubusercontent.com/82720819/115122283-64912f00-9fb7-11eb-9f7f-d4d1b321b77a.png)
![gui](https://user-images.githubusercontent.com/82720819/115122287-6824b600-9fb7-11eb-96eb-5e9dde24653b.png)
![prompt](https://user-images.githubusercontent.com/82720819/115122289-69ee7980-9fb7-11eb-857e-179b5ec07963.png)

**Comment by 1Euro7Cent** [comment]
I think I forgot to add to the README that you need to restart the server (`startServer.bat`) to apply the changes. It only reeds the config in boot up. and BTW I forgot to remove my settings in the config. I just removed them in the executable.zip. That is the reason why it works with skribbl, gartic and paint. So please remove everything in the `config.json` file that does not belong to your settings

**Comment by 4c30** [comment]
sorry, i have tried running startServer.bat, run.exe, and repeating these steps after rebooting the laptop but the issue remains.
i have even tried emptying the json file, and the program still runs and accepts only skribbl, gartic, paint.
it seems like it uses your settings no matter what.

also gui.json shows what i last typed in the gui, but everytime i start it, the text field begins with 'skribbl'

**Comment by 1Euro7Cent** [comment]
First the gui.json is only for sharing the data to the node server. But I might add that the GUI uses the settings to insert them again. Second that problem with the settings not loading is weird. I mean (if you don't done that right) close this window ![image](https://user-images.githubusercontent.com/82720819/115122289-69ee7980-9fb7-11eb-857e-179b5ec07963.png)
and reopen that. If that isn't working ill make a quick fix to load the config every time I/you hit draw (tomorrow. it is very late in my country RN).  I think it is an error in the config.json and not the script itself.

It maybe can be that problem that the files are in the wrong place e.g.: the config.json file not in the server folder

**Comment by 4c30** [comment]
i have deleted the folder and redownloaded, then followed your instructions on restarting the program but the problem is still there
i don't think it's a problem of the script not updating the config, because even after leaving the config empty with "{ }" and restarting the program, it still uses the default settings even if it has nowhere to get them from.
maybe the settings are saved somewhere inside the script itself?  i have no idea though

**Comment by 1Euro7Cent** [comment]
I am adding a debug version. When this is done you can please on the script with the debug mode on. I will notify you when I released that mode. And I added that the GUI loads the last saved stats instead of the default values

**Comment by 1Euro7Cent** [comment]
Done. Please redownload the thing and run the server in debug mode please and please send screenshots of that

**Comment by 4c30** [comment]
ok, i have tried it and it works!

i first started testing an empty config.json:

![debugempty](https://user-images.githubusercontent.com/82720819/115146658-b5586480-a057-11eb-8f0c-3b669100d3aa.png)
![guiempty](https://user-images.githubusercontent.com/82720819/115146674-c2755380-a057-11eb-8342-9cca8d663683.png)
![promptempty](https://user-images.githubusercontent.com/82720819/115146647-ac679300-a057-11eb-86ec-46fab2d2b3de.png)
----------------------------------
then i created a profile named newpaint, and the debug shows it correctly
![debugpaint](https://user-images.githubusercontent.com/82720819/115146712-ed5fa780-a057-11eb-81d3-730a46baa64f.png)
----------------------------------
here is the result next to the prompt after finishing drawing (yes, i have to fiddle with the settings but it works great!)
![promptpaint](https://user-images.githubusercontent.com/82720819/115146713-f05a9800-a057-11eb-87bd-20c293ba3f26.png)
guess i have been rickrolled

thanks for the quick help, feel free to ask me questions or to close the issue!

**Comment by 1Euro7Cent** [comment]
NP. ill, thank you for creating an issue and not just throwing it away. I will add a button to be able to set the values to default BTW.

And feel free to create more issues when you have a problem. And if you have something that I could add let me know
