### ISSUE TITLE
nothing happends when i press draw

### ISSUE THREAD

**Issue by MRlonely3244** [1Euro7Cent/Mrballou-drawbot#21]
and does it work on discord jamspace

**Comment by 1Euro7Cent** [comment]
Have you checked the FAQ?
Look in the console. It should tell you that you need to start the server (drawbot.exe)

If that doesn't help. Send logs. (screenshot of console/s) is enough

**Comment by MRlonely3244** [comment]
![Skjermbilde 2023-05-11 220028](https://github.com/1Euro7Cent/Mrballou-drawbot/assets/122234316/15faf20b-b077-47ee-be70-0fe44ff126b3)

**Comment by MRlonely3244** [comment]
![Skjermbilde 2023-06-02 051959](https://github.com/1Euro7Cent/Mrballou-drawbot/assets/122234316/ae55e830-51e9-48ff-b3c1-b59f2154874a)

**Comment by 1Euro7Cent** [comment]
Can I see the positions.json file. There should be a point called: topLeft and one called bottomRight. These should not be equal

**Comment by 1Euro7Cent** [comment]
Can I see the positions.json file. There should be a point called: topLeft and one called bottomRight. These should not be equal

**Comment by MRlonely3244** [comment]
file:///C:/Users/potet/Downloads/Draw%20bot/positions.json

**Comment by MRlonely3244** [comment]
file:///C:/Users/potet/Downloads/Draw%20bot/positions.json

**Comment by 1Euro7Cent** [comment]
You can open it using notepad. And send a screenshot

**Comment by MRlonely3244** [comment]
![Skjermbilde 2023-06-02 065135](https://github.com/1Euro7Cent/Mrballou-drawbot/assets/122234316/73c3a58f-7991-41cb-977e-ec891cbae6cf)

**Comment by 1Euro7Cent** [comment]
First. You didnt initialized the colors. Second most of your values are -1 that happens when the script cannot get positions. Maby your antivirus is blocking it from reading mouse positions

**Comment by MRlonely3244** [comment]
so what can i do

**Comment by 1Euro7Cent** [comment]
You can try to whitelist "initialize positions.exe" in the antivirus and try initializing again. Dont forget to reboot gui and drawbot.exe

**Comment by MRlonely3244** [comment]
how do i do that with windows security

**Comment by 1Euro7Cent** [comment]
For the to tell you i need to be at my pc. I am on mobile rn. Ill tell you when i have an answer

**Comment by 1Euro7Cent** [comment]
Click [here](https://www.bing.com/search?q=exclude%20a%20folder%20from%20windows%20defender%20scan%20windows%2010%20site:microsoft.com&form=B00032&ocid=SettingsHAQ-BingIA&mkt=en-US) to see how to add exceptions in windows defender

**Comment by MRlonely3244** [comment]
is it the drawbot.exe im going to whitelist

**Comment by 1Euro7Cent** [comment]
no. in this case it is the initializePositions.exe. and rerun that

**Comment by MRlonely3244** [comment]
it work but now it just goes out of the canvas

**Comment by 1Euro7Cent** [comment]
For the canvas thing. Make sure that is set to 100 % 
![image](https://github.com/1Euro7Cent/Mrballou-drawbot/assets/67194495/b1eb5262-3bed-4a46-9985-155f9c1985e5)

**Comment by MRlonely3244** [comment]
i did that but i goes under here i want it
