### ISSUE TITLE
Doesn't use bucket when bucket is set.

### ISSUE THREAD

**Issue by TheUntitledGoose** [1Euro7Cent/Mrballou-drawbot#22]
# Issue: Bucket isn't used.

When as an example going to paint and setting the bucket tool as yes it does exist and setting it to the bucket tool coordinate it never uses it.

Most apparent when drawing a black and white image such as the GitHub logo and it fills in the black with just the pencil tool.

**Comment by 1Euro7Cent** [comment]
Do you have activated the bucket in the gui? If yes show the console output that comes from the server(the one where "listening on port ***" appears)

**Comment by TheUntitledGoose** [comment]
Yes I do have bucket ticked.
![image](https://github.com/1Euro7Cent/Mrballou-drawbot/assets/75637597/30c0206f-325e-4341-b015-a3ba5ede16a8)

**Comment by TheUntitledGoose** [comment]
After some more testing it used the bucket tool for the background. If that's the case then I'm assuming the bucket tool is only used for background, in which case, with the edge detection update would the tool be able to fill the color after outlining?

**Comment by 1Euro7Cent** [comment]
The bot currently only uses the bucket for the color that is most present. In the most cases it is white and it ill be ignored. That shape detection thingy currently is only an idea

**Comment by TheUntitledGoose** [comment]
Would be useful for black and white images, but thanks for the answer. I'll go ahead and close this.
