### ISSUE TITLE
extend it to draw objects in powerpoint

### ISSUE THREAD

**Issue by Yogesh1-11** [1Euro7Cent/Mrballou-drawbot#26]
Hi,
this tool will be really helpful if it can be used to trace outlines from image in powerpoint and then allow user to recolour the shapes. Is it possible?

**Comment by 1Euro7Cent** [comment]
I don't exactly understand what you want from it. It could already draw in the "draw" tab even though only in two colors. Can you describe it even further?

**Comment by 1Euro7Cent** [comment]
Are you still onto it?

**Comment by 1Euro7Cent** [comment]
Closed because of inactivity. Feel free to reopen issue.
