### ISSUE TITLE
Cannot find module axios.cjs

### ISSUE THREAD

**Issue by arti4ikmin** [1Euro7Cent/Mrballou-drawbot#28]
What am I doing wrong or should it be like this?
This is the start.bat since drawbot.exe doesnt even open and add files like in the vid
![Bild_2024-03-03_170255590](https://github.com/1Euro7Cent/Mrballou-drawbot/assets/112105780/c330e33c-4e48-431c-828f-cce5866eed01)

**Comment by 1Euro7Cent** [comment]
Downgrade to Version 3.15.2. the current version seems to have a bug

**Comment by 1Euro7Cent** [comment]
Maybe disabling check for updates fixed it too.

**Comment by 1Euro7Cent** [comment]
Fixed with https://github.com/1Euro7Cent/Mrballou-drawbot/commit/cd307fd35a03cdebccc1b54a9d311b3176591377
