### ISSUE TITLE
The image link almost never works.

### ISSUE THREAD

**Issue by Bossko4537** [1Euro7Cent/Mrballou-drawbot#29]
Most images I get are on google.com urls and the draw bot can't really read those. Try making it use .png or .jpeg images in your files for it to work more correctly.

**Comment by 1Euro7Cent** [comment]
It already uses jpeg and png images. Even base 64 encoded images

**Comment by 1Euro7Cent** [comment]
Is the issue resolved?

**Comment by 1Euro7Cent** [comment]
Closed because of inactivity. Feel free to reopen issue.
