### ISSUE TITLE
Address already in use error 

### ISSUE THREAD

**Issue by Nixias** [1Euro7Cent/Mrballou-drawbot#30]
![image](https://github.com/1Euro7Cent/Mrballou-drawbot/assets/93729501/06e96597-86f6-419a-90f6-7e1f4d079a02)
![image](https://github.com/1Euro7Cent/Mrballou-drawbot/assets/93729501/a7bfe2db-166c-4846-a565-ad008043ec27)

**Comment by 1Euro7Cent** [comment]
You probably already have a instance of the server running. You could close that instance. Or change the port in the config.json file to a different number

**Comment by Nixias** [comment]
> You probably already have a instance of the server running. You could close that instance. Or change the port in the config.json file to a different number

I changed the port to like 25400 and got the same error. I am running it through start.bat so I do not know how i would have another instance open?

**Comment by Nixias** [comment]
I changed the port back but now I'm seeing this?
![image](https://github.com/1Euro7Cent/Mrballou-drawbot/assets/93729501/2ec5c788-2751-4abf-8bae-a5168c8332f4)

**Comment by 1Euro7Cent** [comment]
Did you made the initialization?

**Comment by Nixias** [comment]
what does that mean

**Comment by Nixias** [comment]
Apologies, I have figured ito ut

**Comment by 1Euro7Cent** [comment]
Does it work now?

ima still make an update that when the initialization isn't made that it would say that

**Comment by 1Euro7Cent** [comment]
Closed because of inactivity. Feel free to reopen issue.
