### ISSUE TITLE
Add Functionality for transparent images

### ISSUE THREAD

**Issue by FlipMods** [1Euro7Cent/Mrballou-drawbot#31]
Or / ignore white you should aswell add brightness position options for if there is black it automatically switches the color and when it isn't black put back at full brightness

Example of the slider in question
![image](https://github.com/1Euro7Cent/Mrballou-drawbot/assets/109514575/c06635b7-1cc0-4e1e-b012-b03948784ff7)

**Comment by 1Euro7Cent** [comment]
Good addition. Will add that to the to-do list.

**Comment by 1Euro7Cent** [comment]
By the way. Ignoring white (#FFFFFF) is already possible using the ignore colors tab.

If it doesn't show properly or anything is wrong with it feel free to open another issue

**Comment by 1Euro7Cent** [comment]
Implemented [here](https://github.com/1Euro7Cent/Mrballou-drawbot/releases/tag/3.17.0). it is a beta. So expect some bugs.

**Comment by FlipMods** [comment]
Got it thanks!
