### ISSUE TITLE
Won't use colors and always draw outside the canvas and other problems.

### ISSUE THREAD

**Issue by icedegreaser** [1Euro7Cent/Mrballou-drawbot#36]
the drawbot won't ever uses colors and its always draw outside of the canvas even though i set it at top left and bottom right
in paint, the drawbot can't even choose the right tool to draw and always choose the star shape

**Comment by 1Euro7Cent** [comment]
Look in the FAQ under `It draws outside the boundary and/or not in the right spot`

**Comment by 1Euro7Cent** [comment]
Can you send me the `config.json`, `settings.json` and the `positions.json` file? Or in the new version the zip when clicking the diagnostics button.

**Comment by 1Euro7Cent** [comment]
Closed because of inactivity. Feel free to reopen issue.
