### ISSUE TITLE
Draws slowly

### ISSUE THREAD

**Issue by kallhell4** [1Euro7Cent/Mrballou-drawbot#39]
Sometimes AutoDraw runs slowly and takes much longer to finish the drawings. What could be causing this? Is it possible that the server is crashing?

**Comment by 1Euro7Cent** [comment]
If the server crashes you defiantly will notice that. Make the diagnostics zip file (press the make diagnostics button) and send it to me on dc or mail it to me. 
DC: mrballou
mail: thomasruhl@live.de

**Comment by kallhell4** [comment]
i sent you the diagnostic

**Comment by 1Euro7Cent** [comment]
Is it slowing down mid-draw, over multiple draws or slow in general?
Does the mouse move slowly or isn't the website keeping up with the draw?

Possible fixes I found in your config:
increase the `Distance` value. This will result in less details, but draws faster.

**Comment by kallhell4** [comment]
no its slow in general*
I always run the program with a distance of 2 and a delay of 5, and it draws quickly, but sometimes when the image is too large, the autodraw slows down, and I have to wait 2-3 days each time for it to work properly again.

**Comment by 1Euro7Cent** [comment]
Does it take that long to calculate (after you hit draw and before actual print) or the actual print?

**Comment by kallhell4** [comment]
no, not too much

**Comment by 1Euro7Cent** [comment]
try unchecking line saving mode. it significantly reduces calculation time

**Comment by kallhell4** [comment]
![uy](https://github.com/user-attachments/assets/6858c3e4-8674-42ef-a5ad-c5be4405145f)
i always use this config* and i never check line saving

**Comment by 1Euro7Cent** [comment]
Is it possible to provide a video of it happening?
Or provide the image(s) when this happens.

Some ways to reduce times:
try your image search with `clipart` attached to it

no `clipart` when searching landscape (landscape):
![image](https://github.com/user-attachments/assets/f5f400fd-619a-40ae-b85b-a6ae1b1cc83c)


with `clipart` when searching landscape (clipart landscape):
![image](https://github.com/user-attachments/assets/f0737869-7758-4728-85f3-b2f2e1cefb08)

This reduces the total pixels to draw and allow for the `fast mode` to be more effective. This also reduces calculation times.

Try increasing `distance` and for that zoom in or increase brush size

you can try to look at this value. that is the total amount of instructions it executes (mouse movements). lower is better for speed
![image](https://github.com/user-attachments/assets/bf5d0a83-cf9d-438f-9f47-33e8ef875cce)

**Comment by kallhell4** [comment]
I use this image a lot, and it usually works well, but once the autodraw crashes, it draws the logo slowly. But it's strange—when I recorded it, the autodraw worked normally.

image link : https://cdn.freebiesupply.com/logos/large/2x/superman-6-logo-png-transparent.png


https://github.com/user-attachments/assets/3e4964ee-ec97-476a-ac4c-204247a6692b

**Comment by kallhell4** [comment]
yea no sorry craches is a wrong word*, for me, the crash is when the autodraw starts drawing slowly.
(sry for my english/ not native lol)

**Comment by 1Euro7Cent** [comment]
My English is not native too btw.

I literally cannot figure out why this is happening. It is late anyways here rn.  Send it when you have it. I'll look into it tomorrow.

**Comment by kallhell4** [comment]
Yea thxx bro !!*

**Comment by kallhell4** [comment]
I think i fixed it*!! thx 4 ur help 💯

**Comment by 1Euro7Cent** [comment]
For the record. What was the issue, and what fixed it?
