### ISSUE TITLE
Is this safe?

### ISSUE THREAD

**Issue by 5Brewed** [1Euro7Cent/Mrballou-drawbot#40]
Is the program a virus, and if you claim it is not. Back it up with proof.

Edit: i saw the comment thread of if its a virus or not on reddit, but im going to use it in my vm first :D

**Comment by 1Euro7Cent** [comment]
It is safe. I cannot send you proof because the biggest proof is that the full code of it is public and can be viewed and changed by everyone. If you don't trust me or the code, don't use it. You can go line by line and look if it has a virus or suspicious code.

**Comment by 5Brewed** [comment]
Thank you! I am also the egg commenter so thanks alot for the help, i think ill install it :D

**Comment by 5Brewed** [comment]
I also checked it on my VM and it didnt show anything suspicious, it got a seven score for moving mouse tho.  (expected)
VM used: Tria.ge

**Comment by SPLATPLAYS** [comment]
@1Euro7Cent @5Brewed Close this question?
