### ISSUE TITLE
Bot doesn't use colors on certain sites.

### ISSUE THREAD

**Issue by BafflingSpy3294** [1Euro7Cent/Mrballou-drawbot#42]
Such as sites that have a colour wheel that need to be pressed to obtain colours.
![Example](https://github.com/user-attachments/assets/f3abeb12-119d-4825-9cf0-5153cd6c4c1d) ![image](https://github.com/user-attachments/assets/1dc30ae3-ac8c-41f6-a88e-c0adf0f92673)

Like my Strawpage for example, the bot doesn't press on the colour wheel, only pressing where I set the colours to be.
So the entire drawing is one colour.
![image](https://github.com/user-attachments/assets/756fac64-8d4c-4cbd-9fd2-20cecc8991c8)

Do you think you can fix this by adding the option for the bot to click on the colour wheel, then select the colour, instead of it printing in one colour when drawing on sites that requires to click to access colour?
![image](https://github.com/user-attachments/assets/dcd9b106-90ea-4e5c-afd3-9c61e72bd238)

**Comment by 1Euro7Cent** [comment]
Thank you for the detailed issue. Can you send me diagnostics (pressing the make diagnostic button). Because the bot never draws with only one color if it has more.

**Comment by 1Euro7Cent** [comment]
And can you name the site/program you try to draw in?

**Comment by BafflingSpy3294** [comment]
Sorry for not responding, the hurricane hit. Let me do that for you. 👍🏾

**Comment by BafflingSpy3294** [comment]
Was trying the bot out on strawpage [Basically a website builder, with a draw option]:
https://straw.page/ (Is the site)

Here's my the diagnostic:
[diagnostic.zip](https://github.com/user-attachments/files/17335417/diagnostic.zip)
![image](https://github.com/user-attachments/assets/2c494c70-25b0-48ee-b57d-009a32e1d0bc)


![waltre-wite](https://github.com/user-attachments/assets/2ea80103-5aa5-4462-8cb5-ab902cfa0821)

**Comment by 1Euro7Cent** [comment]
Sorry for the late response. I just now was able to process this issue. I think it's a configuration problem. ~Rerun the initialize position and when it asks if you need to click to open, then type y for yes.~ I noticed a bug in the configuration program. I am now making a fix for that. After I publish the fix please rerun the initialize positions program.

**Comment by 1Euro7Cent** [comment]
Pushed a bug fix. [Here](https://github.com/1Euro7Cent/Mrballou-drawbot/releases/tag/3.20.1) it is

oh and btw i got the rainbow working on the site:

![image](https://github.com/user-attachments/assets/b39ae4bd-3736-4627-b612-ef9c059291b7)

**Comment by BafflingSpy3294** [comment]
Sick! Thanks bro.
![image](https://github.com/user-attachments/assets/1e237886-416c-410f-ab6a-fc7e59414a3f)
