### ISSUE TITLE
Drawbot won't open

### ISSUE THREAD

**Issue by Delsys32pls** [1Euro7Cent/Mrballou-drawbot#46]
(Windows 10, using NodeJS)

Probably just an issue on my part but

Tries to click to open Drawbot > CMD opens up > Displays "This is the GUI" screen that usually appears when you open the gui > closes (this is within the span of a second)

I have no idea want to do since I've been suffering with my JS and PY ever since i tried to get this working lol, suggestions would be cool until i get this working tho

**Comment by 1Euro7Cent** [comment]
Try opening with the bat file that is included. There is a "pause" command at the end, so it doesn't close after it crashes.

**Comment by Delsys32pls** [comment]
> Try opening with the bat file that is included. There is a "pause" command at the end, so it doesn't close after it crashes.

Yep, already been trying that, no dice

**Comment by 1Euro7Cent** [comment]
are you running the exe or the js file?

**Comment by Delsys32pls** [comment]
the exe

**Comment by 1Euro7Cent** [comment]
try opening a cmd in the folder and then typing ./drawbot.exe so it will start it in the cmd window, so it doesnt close after it crashes

**Comment by Delsys32pls** [comment]
I don't think it worked

**Comment by 1Euro7Cent** [comment]
do you have any way of seeing what the console says

**Comment by Delsys32pls** [comment]
managed to get a screenshot

![image](https://github.com/user-attachments/assets/1183a0e5-3578-4dcd-9538-7f4e7e1a2100)

**Comment by Delsys32pls** [comment]
I'm pretty sure this is all that pops up before it crashes

**Comment by 1Euro7Cent** [comment]
have you used the "save" feature of the bot?

**Comment by Delsys32pls** [comment]
I'm pretty sure not, its blank in there besides the {}

If it helps, other JS files I've tried running recently have just been crashing upon opening

**Comment by 1Euro7Cent** [comment]
i mean. i dont know what to do about it. it should work. you could try deleting the file and see if that helps

**Comment by Delsys32pls** [comment]
Alright, thanks for the help though
