### ISSUE TITLE
draw not working, some errors appear

### ISSUE THREAD

**Issue by uhcool** [1Euro7Cent/Mrballou-drawbot#5]
Nothin happens when I press draw and I assume has to do something with the errors that appear in a cmd line when I open up startAll.
[Screenshot 2021-05-19 170344](https://user-images.githubusercontent.com/84479746/118890444-496e5380-b8c4-11eb-9324-0f6dfcafab73.png)

**Comment by 1Euro7Cent** [comment]
Fixed. You don't need to redo the initialization
