### ISSUE TITLE
GUI wont open

### ISSUE THREAD

**Issue by BamBoozledMC** [1Euro7Cent/Mrballou-drawbot#6]
`C:\Users\****\Downloads\draw bot\release data>echo off
Traceback (most recent call last):
  File "gui.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Press any key to continue . . .`

I've already tried installing requests multiple times

**Comment by 1Euro7Cent** [comment]
Was the installation of the module successfull? If not please fix that by yourself. That isnt a error of my side.

If it successfully installed it should work. Maybe you installed it to a diffrent python version?

**Comment by BamBoozledMC** [comment]
> Was the installation of the module successfull? If not please fix that by yourself. That isnt a error of my side.
> 
> If it successfully installed it should work. Maybe you installed it to a diffrent python version?

I have the correct python version installed.
When i install it, it says something like it already exists in python directory

**Comment by 1Euro7Cent** [comment]
I mean did you installed the module to the correct python version. E.g: pip3.8 install ... is not the same as pip3.7 install ... to open the gui i use the command python <filename>. Maybe change that or install the module to pip install ...

**Comment by BamBoozledMC** [comment]
> I mean did you installed the module to the correct python version. E.g: pip3.8 install ... is not the same as pip3.7 install ... to open the gui i use the command python <filename>. Maybe change that or install the module to pip install ...

I used `pip install requests` in the directory, like you said in readme

**Comment by BamBoozledMC** [comment]
![image](https://user-images.githubusercontent.com/64771089/125896904-b46d5bf7-6b14-4e46-b142-17cf219429fb.png)

**Comment by 1Euro7Cent** [comment]
Maybe try pip3.9 install ...

**Comment by BamBoozledMC** [comment]
> Maybe try pip3.9 install ...

I just did same error

**Comment by 1Euro7Cent** [comment]
Try python3.9 gui.py

**Comment by BamBoozledMC** [comment]
'python3.9' is not recognized as an internal or external command

**Comment by 1Euro7Cent** [comment]
Maybe this can help: https://github.community/t/python-modulenotfounderror-although-module-is-installed-aiohttp/15425 . I cannot respond for the next few hours bc of scool

**Comment by 1Euro7Cent** [comment]
Too inactive. Closing issue. Feel free to reopen when you still have something to contribute to this issue.
