### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by OrangeSucculenc** [1Euro7Cent/Mrballou-drawbot#7]
While this isn't exactly an issue but more of a suggestion, Imma still put this here.

Basically, it would be very nice to have a "disable white" option, aka it doesn't draw any of the white pixels. this is useful for a cool drawing game I found, but in there you can only use black and white and there is no erasing, so it draws both the white and black as black.

**Comment by 1Euro7Cent** [comment]
Your request is updated in the new beta. But you need to figure out how to run that. It is pretty similar BTW.

**Comment by 1Euro7Cent** [comment]
The bot ignores by default white. When using buckets it is ignoring that color.

In the GUI the line ignore color does nothing atm

Closing issue. Feel free to reopen when you still have something to contribute to this issue.
