### ISSUE TITLE
Colours not registering

### ISSUE THREAD

**Issue by adamalbu** [1Euro7Cent/Mrballou-drawbot#8]
The colours won't register propely. When I hover over a colour, it usually appears as #ffffff no matter what colour the cursor is over

**Comment by 1Euro7Cent** [comment]
That is a known bug. You need to be in that window to register the color. I don't know how to fix that. That isn't a problem on my side.

**Comment by adamalbu** [comment]
> That is a known bug. You need to be in that window to register the color. I don't know how to fix that. That isn't a problem on my side.
So you mean the window need to be selected while I'm registering the colours?

**Comment by adamalbu** [comment]
Ok, I'll try that.

**Comment by adamalbu** [comment]
> That is a known bug. You need to be in that window to register the color. I don't know how to fix that. That isn't a problem on my side.

Do you mean the initialisation window or the window I am picking from (paint)?

**Comment by 1Euro7Cent** [comment]
I mean the paint program. And what offset?

**Comment by adamalbu** [comment]
> I mean the paint program. And what offset?

When I try selecting a colour, the picker offsets, so when I try moving the cursor down, it pick a color somewhere above it

**Comment by 1Euro7Cent** [comment]
The color is being picked at the top left at the tip of the mouse

**Comment by adamalbu** [comment]
> The color is being picked at the top left at the tip of the mouse

I know but the colour picks higher than the actual mouse.

**Comment by adamalbu** [comment]
I'll try again tomorrow.

**Comment by adamalbu** [comment]
Here is a screenshot of my problem:
![image](https://user-images.githubusercontent.com/45970222/155133248-df3a24b3-57c4-44f7-a108-3ec455769e05.png)

**Comment by adamalbu** [comment]
I've changed my resolution to 1600 x 900 and now it works perfectly fine.
