### ISSUE TITLE
Are you almost done with V2?

### ISSUE THREAD

**Issue by IdkwhyImadethisacc** [1Euro7Cent/Mrballou-drawbot#9]
Hi I was just wondering if you have any idea when your V2 version of the auto drawer will come out, that is all I have to say, goodbye.

**Comment by 1Euro7Cent** [comment]
If you didnt saw it. There is a v2 branch. It works but is not done or documented.

**Comment by 1Euro7Cent** [comment]
Too inactive. Closing issue. Feel free to reopen when you still have something to contribute to this issue.
